# Generated by Django 5.2.5 on 2025-10-08 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='Image',
        ),
        migrations.AddField(
            model_name='problem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='problems/'),
        ),
    ]
