# Generated by Django 5.2.8 on 2025-11-18 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetag',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal válido, por ejemplo: #ff0000', regex='^#([A-Fa-f0-9]{6})$')]),
        ),
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solutions', to='MainApp.problem'),
        ),
    ]
