# Generated by Django 5.2.8 on 2025-11-18 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_typetag_color_alter_solution_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typetag',
            name='color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal válido, por ejemplo: #ff0000', regex='^#([A-Fa-f0-9]{6})$')]),
        ),
    ]
