# Generated by Django 4.2.27 on 2026-02-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type_tags',
            field=models.ManyToManyField(blank=True, to='MainApp.typetag'),
        ),
    ]
