# Generated by Django 4.2.27 on 2026-06-09 18:34

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_add_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
