# Generated by Django 5.2.8 on 2025-11-18 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_typetag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='diftag',
            name='color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingrese un color hexadecimal válido, por ejemplo: #ff0000', regex='^#([A-Fa-f0-9]{6})$')]),
        ),
    ]
