# Generated by Django 5.2.5 on 2025-10-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_tag_problem_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TypeTag',
        ),
    ]
