# Generated by Django 5.2.8 on 2025-11-20 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_diftag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='dif_tags',
        ),
        migrations.AddField(
            model_name='problem',
            name='dif_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.diftag'),
        ),
    ]
