# Generated by Django 5.2.5 on 2025-10-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_rename_tag_typetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='tags',
            new_name='type_tags',
        ),
        migrations.AddField(
            model_name='problem',
            name='dif_tags',
            field=models.ManyToManyField(to='MainApp.diftag'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.problem')),
            ],
        ),
    ]
