# Generated by Django 5.2.5 on 2025-10-13 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_diftag_rename_tags_problem_type_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soluciones', to='MainApp.problem'),
        ),
    ]
