# Generated by Django 5.2.8 on 2025-11-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_remove_problem_dif_tags_problem_dif_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
