# Generated by Django 5.2.5 on 2025-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_solution_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
