# Generated by Django 5.2.8 on 2025-11-26 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_bundle_author_problem_author_alter_problem_type_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_bundles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bundle',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
