# Generated by Django 5.2.5 on 2025-11-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_problem_likes_problem_likes_count_alter_problem_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
