# Generated by Django 5.2.8 on 2025-11-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_bundle_likes_bundle_likes_count_alter_problem_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diftag',
            name='name',
            field=models.FloatField(),
        ),
    ]
