# Generated by Django 4.2.27 on 2026-01-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_diftag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='needs_reload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle',
            name='relodeable',
            field=models.BooleanField(default=False),
        ),
    ]
