# Generated by Django 4.2.27 on 2026-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_bundle_needs_reload_bundle_relodeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
